BUG: use more robust method to determine gh login name
Avoid bug on some macs decoding gh output (probably because
emoji checkmark is used in gh auth status result).

The new method uses json to avoid encoding issues.

```
Traceback (most recent call last):

File "/Users/amaga/SlicerMorphoDepot/MorphoDepotReview/MorphoDepotReview.py", line 106, in updatePRList

prList = self.logic.prList(role="reviewer")

File "/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 326, in prList

me = self.gh("auth status").split("\n")[1].split()[-2] # TODO better way?

File "/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 301, in gh

result = process.communicate()

File "/Users/amaga/Desktop/Slicer.app/Contents/lib/Python/lib/python3.9/subprocess.py", line 1121, in communicate

stdout = self.stdout.read()

File "/Users/amaga/Desktop/Slicer.app/Contents/bin/../lib/Python/lib/python3.9/encodings/ascii.py", line 26, in decode

return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13: ordinal not in range(128)
```